In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

In [2]:
df = pd.read_csv('Cardetails.csv')

In [3]:
df.head(6)

name  year  selling_price  km_driven    fuel  \
0         Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1   Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2       Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3      Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4         Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
5  Hyundai Xcent 1.2 VTVT E Plus  2017         440000      45000  Petrol   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   
2  Individual       Manual   Third Owner   17.7 kmpl  1497 CC      78 bhp   
3  Individual       Manual   First Owner   23.0 kmpl  1396 CC      90 bhp   
4  Individual       Manual   First Owner   16.1 kmpl  1298 CC    88.2 bhp   
5  Individual       Manual   First Owner  20.14 kmpl  1197 CC   81.86 bhp   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0  
5         113.75nm@ 4000rpm    5.0

In [4]:
df.tail(6)

name  year  selling_price  km_driven    fuel  \
8122  Hyundai i20 Magna 1.4 CRDi  2014         475000      80000  Diesel   
8123           Hyundai i20 Magna  2013         320000     110000  Petrol   
8124       Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125      Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126             Tata Indigo CR4  2013         290000      25000  Diesel   
8127             Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage   engine  \
8122  Individual       Manual          Second Owner  22.54 kmpl  1396 CC   
8123  Individual       Manual           First Owner   18.5 kmpl  1197 CC   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl  1493 CC   
8125  Individual       Manual           First Owner   19.3 kmpl  1248 CC   
8126  Individual       Manual           First Owner  23.57 kmpl  1396 CC   
8127  Individual       Manual           First Owner  23.57 kmpl  1396 CC   

      max_power                     torque  seats  
8122  88.73 bhp      219.7Nm@ 1500-2750rpm    5.0  
8123  82.85 bhp           113.7Nm@ 4000rpm    5.0  
8124    110 bhp  24@ 1,900-2,750(kgm@ rpm)    5.0  
8125   73.9 bhp             190Nm@ 2000rpm    5.0  
8126     70 bhp        140Nm@ 1800-3000rpm    5.0  
8127     70 bhp        140Nm@ 1800-3000rpm    5.0

In [5]:
df.drop(columns=['torque'], inplace=True)

In [6]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'seats'],
      dtype='object')

In [7]:
df.head(2)

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   

   seats  
0    5.0  
1    5.0

In [8]:
df.shape

(8128, 12)

In [9]:
df.dropna(inplace=True)

In [10]:
df.shape

(7907, 12)

In [11]:
df.duplicated().sum()

np.int64(1189)

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           6718 non-null   object 
 1   year           6718 non-null   int64  
 2   selling_price  6718 non-null   int64  
 3   km_driven      6718 non-null   int64  
 4   fuel           6718 non-null   object 
 5   seller_type    6718 non-null   object 
 6   transmission   6718 non-null   object 
 7   owner          6718 non-null   object 
 8   mileage        6718 non-null   object 
 9   engine         6718 non-null   object 
 10  max_power      6718 non-null   object 
 11  seats          6718 non-null   float64
dtypes: float64(1), int64(3), object(8)
memory usage: 682.3+ KB


In [14]:
def get_brand_name(car_name):
    car_name = car_name.split(' ')[0]
    return car_name.strip()

In [15]:
def clean_data(value):
    value = value.split(' ')[0]
    value = value.strip()
    if value == '':
        value = 0
    return float(value)

In [16]:
get_brand_name('Maruti  Swift Dzire VDI')

'Maruti'

In [17]:
df['name'] = df['name'].apply(get_brand_name)

In [18]:
df['name'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'], dtype=object)

In [19]:
df['mileage'] = df['mileage'].apply(clean_data)

In [20]:
df['max_power'] = df['max_power'].apply(clean_data)

In [21]:
df['engine'] = df['engine'].apply(clean_data)

In [68]:
df['name']=df['name'].replace(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'],
                          [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
                          ).astype(int)

In [23]:
df['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [67]:
df['transmission'] = df['transmission'].replace(['Manual', 'Automatic'], [1, 2]).astype(int)


In [25]:
df['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [66]:
df['seller_type'] = df['seller_type'].replace(['Individual', 'Dealer', 'Trustmark Dealer'], [1, 2, 3]).astype(int)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           6718 non-null   int64  
 1   year           6718 non-null   int64  
 2   selling_price  6718 non-null   int64  
 3   km_driven      6718 non-null   int64  
 4   fuel           6718 non-null   object 
 5   seller_type    6718 non-null   int64  
 6   transmission   6718 non-null   int64  
 7   owner          6718 non-null   object 
 8   mileage        6718 non-null   float64
 9   engine         6718 non-null   float64
 10  max_power      6718 non-null   float64
 11  seats          6718 non-null   float64
dtypes: float64(4), int64(6), object(2)
memory usage: 682.3+ KB


In [28]:
df['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [65]:
df['fuel'] = df['fuel'].replace(['Diesel', 'Petrol', 'LPG', 'CNG'], [1, 2, 3, 4])

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           6718 non-null   int64  
 1   year           6718 non-null   int64  
 2   selling_price  6718 non-null   int64  
 3   km_driven      6718 non-null   int64  
 4   fuel           6718 non-null   int64  
 5   seller_type    6718 non-null   int64  
 6   transmission   6718 non-null   int64  
 7   owner          6718 non-null   object 
 8   mileage        6718 non-null   float64
 9   engine         6718 non-null   float64
 10  max_power      6718 non-null   float64
 11  seats          6718 non-null   float64
dtypes: float64(4), int64(7), object(1)
memory usage: 682.3+ KB


In [31]:
df.reset_index(inplace=True)

In [32]:
df.head()

index  name  year  selling_price  km_driven  fuel  seller_type  \
0      0     1  2014         450000     145500     1            1   
1      1     2  2014         370000     120000     1            1   
2      2     3  2006         158000     140000     2            1   
3      3     4  2010         225000     127000     1            1   
4      4     1  2007         130000     120000     2            1   

   transmission         owner  mileage  engine  max_power  seats  
0             1   First Owner    23.40  1248.0      74.00    5.0  
1             1  Second Owner    21.14  1498.0     103.52    5.0  
2             1   Third Owner    17.70  1497.0      78.00    5.0  
3             1   First Owner    23.00  1396.0      90.00    5.0  
4             1   First Owner    16.10  1298.0      88.20    5.0

In [33]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [64]:
df['owner'] = df['owner'].replace(
    ['First Owner', 'Second Owner', 'Third Owner', 'Fourth & Above Owner', 'Test Drive Car'],
    [1, 2, 3, 4, 5]
).astype(int)

In [35]:
df.drop(columns=['index'], inplace=True)

In [36]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
seats            0
dtype: int64

In [37]:
x = df.drop(columns=['selling_price'])
y =df['selling_price']

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [39]:
#LinearRegressio

In [40]:
li_model = LinearRegression()

In [41]:
li_model.fit(x_train, y_train)

LinearRegression()

In [42]:
y_pred = li_model.predict(x_test)

In [43]:
y_pred

array([ 771222.5869167 ,  680626.30204719,  532211.36059466, ...,
       1061558.84250501, -239241.24473114,   52377.60034125])

In [44]:
mae_li=mean_absolute_error(y_test,y_pred)

In [45]:
mae_li

np.float64(166791.388086638)

In [46]:
r2_li=r2_score(y_test,y_pred)

In [47]:
r2_li

0.6619521189811719

In [48]:
#RandomForestRegressor

In [49]:
rf_model = RandomForestRegressor(n_estimators=25, random_state=42)

In [50]:
rf_model.fit(x_train,y_train)

RandomForestRegressor(n_estimators=25, random_state=42)

In [51]:
y2_pred=rf_model.predict(x_test)

In [52]:
y2_pred

array([445720.  , 732800.  , 524159.92, ..., 918400.  , 128460.  ,
       245200.  ])

In [53]:
mae_rf=mean_absolute_error(y_test,y2_pred)

In [54]:
mae_rf

np.float64(73845.94288157923)

In [55]:
r2_rf=r2_score(y_test,y2_pred)

In [56]:
r2_rf

0.8988349153362034

In [57]:
df

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0        1  2014         450000     145500     1            1             1   
1        2  2014         370000     120000     1            1             1   
2        3  2006         158000     140000     2            1             1   
3        4  2010         225000     127000     1            1             1   
4        1  2007         130000     120000     2            1             1   
...    ...   ...            ...        ...   ...          ...           ...   
6713     1  2013         260000      50000     2            1             1   
6714     4  2014         475000      80000     1            1             1   
6715     4  2013         320000     110000     2            1             1   
6716     4  2007         135000     119000     1            1             1   
6717     1  2009         382000     120000     1            1             1   

      owner  mileage  engine  max_power  seats  
0         1    23.40  1248.0      74.00    5.0  
1         2    21.14  1498.0     103.52    5.0  
2         3    17.70  1497.0      78.00    5.0  
3         1    23.00  1396.0      90.00    5.0  
4         1    16.10  1298.0      88.20    5.0  
...     ...      ...     ...        ...    ...  
6713      2    18.90   998.0      67.10    5.0  
6714      2    22.54  1396.0      88.73    5.0  
6715      1    18.50  1197.0      82.85    5.0  
6716      4    16.80  1493.0     110.00    5.0  
6717      1    19.30  1248.0      73.90    5.0  

[6718 rows x 12 columns]

In [58]:
x_train.head(1)

name  year  km_driven  fuel  seller_type  transmission  owner  mileage  \
2481     3  2008     110000     2            1             1      2     17.7   

      engine  max_power  seats  
2481  1497.0       78.0    5.0

In [59]:
input_data_model = pd.DataFrame(
    [[1,	2014, 145500,	1,	1,	1,	1,	23.40,	1248.0,	74.00,	5.0]],
    columns=['name','year','km_driven','fuel','seller_type','transmission','owner','mileage','engine','max_power','seats'])

In [60]:
input_data_model

name  year  km_driven  fuel  seller_type  transmission  owner  mileage  \
0     1  2014     145500     1            1             1      1     23.4   

   engine  max_power  seats  
0  1248.0       74.0    5.0

In [61]:
rf_model.predict(input_data_model)

array([468999.84])

In [62]:
import pickle as pk

In [63]:
pk.dump(rf_model,open('model.pkl','wb'))